details:
  namespace: training10-bookinfo-prd
  image: registry.demo.opsta.co.th/training10/bookinfo/details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes_io_ingress_class: nginx
    nginx_ingress_kubernetes_io_rewrite_target: /$2
  host: bookinfo.opsta.co.th
  path: "/training10/details(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  COMMIT_ID: CHANGEME
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-details-mongodb:27017/details
